commitizen:
  name: cz_conventional_commits
  version: 0.1.0
  tag_format: v$version
  update_changelog_on_bump: false
  changelog_file: "CHANGELOG.md"
  changelog_incremental: false
  version_files: ["CHANGELOG.md"]
  changelog_message_template: |
    ## [Unreleased]
    ### Added
    - {{ message }}

    ### Changed
    ### Fixed